<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="OSO-DTP-057" name="Nationality Master" tests="4" failures="1" timestamp="16 Nov 2017 05:06:19 GMT" time="200.165" errors="0">
  <testcase name="Login" time="1.818" classname="Module.RegionalSetup.TC010_NationalityMasterUploadData"/>
  <testcase name="Target_Page" time="77.562" classname="Module.RegionalSetup.TC010_NationalityMasterUploadData"/>
  <testcase name="AddNew_Button" time="36.217" classname="Module.RegionalSetup.TC010_NationalityMasterUploadData"/>
  <testcase name="Data_Upload" time="8.325" classname="Module.RegionalSetup.TC010_NationalityMasterUploadData">
    <failure type="java.lang.AssertionError" message="Expected : [Record Saved Successfully.] But Found : [Nationality Code Already Exists.]">
      <![CDATA[java.lang.AssertionError: Expected : [Record Saved Successfully.] But Found : [Nationality Code Already Exists.]
	at Module.RegionalSetup.TC010_NationalityMasterUploadData.Data_Upload(TC010_NationalityMasterUploadData.java:88)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Data_Upload -->
</testsuite> <!-- Nationality Master -->
