<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OSO-DTP-057" name="Module.GeneralSetup.TC003_UploadMaster" tests="3" failures="1" timestamp="16 Nov 2017 05:49:36 GMT" time="404.464" errors="0">
  <testcase name="Target_Page" time="72.014" classname="Module.GeneralSetup.TC003_UploadMaster"/>
  <testcase name="Login" time="3.304" classname="Module.GeneralSetup.TC003_UploadMaster"/>
  <testcase name="Data_Upload" time="329.146" classname="Module.GeneralSetup.TC003_UploadMaster">
    <failure type="java.lang.AssertionError" message="Page crashed : Alert Box Not Present expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Page crashed : Alert Box Not Present expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at pom.ObjectPages.uiActions.UploadMasterRevised.Test_data_upload(UploadMasterRevised.java:98)
	at Module.GeneralSetup.TC003_UploadMaster.Data_Upload(TC003_UploadMaster.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Data_Upload -->
</testsuite> <!-- Module.GeneralSetup.TC003_UploadMaster -->
