<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OSO-DTP-057" name="Module.RegionalSetup.TC010_NationalityMasterUploadData" tests="4" failures="1" timestamp="16 Nov 2017 05:49:36 GMT" time="132.949" errors="0">
  <testcase name="AddNew_Button" time="38.410" classname="Module.RegionalSetup.TC010_NationalityMasterUploadData"/>
  <testcase name="Login" time="3.955" classname="Module.RegionalSetup.TC010_NationalityMasterUploadData"/>
  <testcase name="Target_Page" time="79.725" classname="Module.RegionalSetup.TC010_NationalityMasterUploadData"/>
  <testcase name="Data_Upload" time="10.859" classname="Module.RegionalSetup.TC010_NationalityMasterUploadData">
    <failure type="java.lang.AssertionError" message="Expected : [Record Saved Successfully.] But Found : [Nationality Code Already Exists.]">
      <![CDATA[java.lang.AssertionError: Expected : [Record Saved Successfully.] But Found : [Nationality Code Already Exists.]
	at org.testng.Assert.fail(Assert.java:94)
	at Module.RegionalSetup.TC010_NationalityMasterUploadData.Data_Upload(TC010_NationalityMasterUploadData.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Data_Upload -->
</testsuite> <!-- Module.RegionalSetup.TC010_NationalityMasterUploadData -->
