<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OSO-DTP-057" name="Module.GeneralSetup.TC007_CountryMasterUploadData" tests="5" failures="2" timestamp="5 Sep 2017 12:32:39 GMT" time="84.299" errors="0">
  <testcase name="Target_Page" time="18.562" classname="Module.GeneralSetup.TC007_CountryMasterUploadData"/>
  <testcase name="AddNew_Button" time="20.160" classname="Module.GeneralSetup.TC007_CountryMasterUploadData"/>
  <testcase name="Login" time="26.158" classname="Module.GeneralSetup.TC007_CountryMasterUploadData"/>
  <testcase name="Data_Upload" time="12.214" classname="Module.GeneralSetup.TC007_CountryMasterUploadData">
    <failure type="java.lang.AssertionError" message="Expected : [Record Saved Successfully.] But Found : Invalid Number: Time Difference">
      <![CDATA[java.lang.AssertionError: Expected : [Record Saved Successfully.] But Found : Invalid Number: Time Difference
	at org.testng.Assert.fail(Assert.java:94)
	at Module.GeneralSetup.TC007_CountryMasterUploadData.Data_Upload(TC007_CountryMasterUploadData.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Data_Upload -->
  <testcase name="Data_Upload" time="7.205" classname="Module.GeneralSetup.TC007_CountryMasterUploadData">
    <failure type="java.lang.AssertionError" message="Expected : [Record Saved Successfully.] But Found : Invalid Number: Time Difference">
      <![CDATA[java.lang.AssertionError: Expected : [Record Saved Successfully.] But Found : Invalid Number: Time Difference
	at org.testng.Assert.fail(Assert.java:94)
	at Module.GeneralSetup.TC007_CountryMasterUploadData.Data_Upload(TC007_CountryMasterUploadData.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:391)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Data_Upload -->
</testsuite> <!-- Module.GeneralSetup.TC007_CountryMasterUploadData -->
